export default {
    about_us:'About Us',
    contact_details:'Contact Details',
    email:'Email :',
    phone:'Phone :',
    driver_account_approve_err:'Your account is not approved yet as a service provider.',
    account_not_exsist:'Your account does not exist as a service provider',
    driver_ride_complete_status:' Beeplink man has Completed the work. your request id is',
    please_wait:'Calculating your fare',
    on_trip:'Your Fare',
    complete_trip:'COMPLETE',
    account_successful_done:'Your account has been successfully created and waiting for approve confirmation by admin.',
    image_size_error:'Image Size should not be greater than 2mb.',
    password_blank_error:'Password can\'t be blank.',
    password_complexity_alphabet:'Password must consists of at least 1 alphanumeric characters and 8-15 length.',
    password_complexity_complex:'Password must be atleast 1 Capital letter,1 small-case letter, 1 digit and 1 special character with 6-10 length.',
    driver_registration:'Service Provider Registration',
    first_name:'First Name',
    first_name_error:'Please enter your first name',
    last_name:'Last Name',
    last_name_error:'Please enter your last name',
    email:'Email',
    email_blank_error:'Please enter a valid email address',
    mobile:'Mobile Number',
    mobile_no_blank_error:'Please enter mobile number',
    password:'Password',
    confrim_password:'Confirm Password',
    password_not_match:'Password does not match',
    about_me:'About Me',
    account_type:'Account type',
    categories:'Categories',
    vehicle_model_name:'Vehicle Model Name',
    vehicle_model_name_blank_error:'Vehicle Name Can\'t be blank',
    vehicle_reg_no:'Vehicle Registration Number',
    vehicle_number_blank_err:'Vehicle number Can\'t be blank',
    upload_driving_lisence:'Upload your Driving License',
    image_size_warning:'(Image size: Max 2 MB)',
    reg_no:'Submit',
    update_profile:'Upadate Profile',
    valid_mobile_number:'Please enter a valid mobile number',
    update_now:'Update Now',
    no_notification:'No notification found',
    forgot_password:'Forgot Password?',
    valid_email_err:'Please enter a valid email address',
    send_email:'Send Email',
    enter_code:'Enter the code',
    submit:'Submit',
    change_password:'Change Password ?',
    old_password:'Old Password',
    old_password_err:'Please enter a old password',
    new_password:'New Password',
    new_password_err:'Please enter a new password',
    update:'Update',
    login:'Login',
    booking_request:'Requests For Approval',
    my_service: 'Messages Settings',
    profile_settings:'Profile Settings',
    incomeText:"My Earnings",
    my_bookings:'Approved Requests',
    about_us:'About Us',
    sign_out:'Log out',
    logout: 'Logout',
    rider_ride_cancel_text:'Customer has cancelled the request',
    mobile_no_found:'Mobile Number Not found',
    otp_error:'Please enter the correct OTP',
    driver_journey_err:'Beeplink man started the work. your request id is',
    on_trip:'Your Fare',
    wait_for_rider:'WAIT FOR CUSTOMER',
    rider_notified:'Customer has been notifed',
    start_trip:'START WORK',
    cancel_reson_1:'Unable to Contact Driver',
    cancel_reson_2:'Cab is not moving in my direction',
    cancel_reson_3:'My reason is not listed',
    cancel_reson_4:'Driver Denied duty',
    cancel_reson_5:'Cab is not coming on expected time',
    api_error:'Google places API Error',
    accept_booking_request:' Has Accepted Your Request',
    pickup_location:'pickup location',
    drop_location:'drop location',
    ignore_text:'Ignore',
    modal_close:'Modal has been closed.',
    alert_text:'Alert',
    ignore_job_title:'Do you want to ignore this request?',
    cancel:'Cancel',
    ok:'OK',
    accept:'Accept',
    task_list:'Requests For Approval',
    rider_not_here:'There are currently no requests from people in your area. As soon as a request will be received, you will be notified about it.',
    booking_request_rejected:'Your booking request has rejected by requested driver',
    driver_requested_for_payment:'Beeplink man has requested for payment. your request id is',
    request_payment:'REQUEST PAYMENT',
    my_rides:'My Rides',
    password_reset_link:'A Password Reset Link sent to your email please check and reset your New Password.',
    notification:'Notifications',
    chat_blank:'please write something...',
    send_msg:', sent a messege to you: \n',
    driver:' ',
    chat_history_not_found:'No chat history found',
    chat:'Chat',
    send:'Send',
    type_messege:'Type your messege',
    photo_upload_action_sheet_title:'Choose a Media Type ?',
    camera:'Camera',
    galery:'Gallery',
    cancel:'Cancel',
    yes:'Yes',
    password_change:'You Password successfully updated',
    password_not_match:'password does not match',
    confrim:'Confrimation',
    delete_account:'Do you want to delete your account ?',
    my_profile:'My Profile',
    active_status:'Available for messages?',
    profile_details:'Profile Details',
    location:'Location',
    mobile_no:'Mobile Number',
    preffered_lang:'Preferred Language',
    lang:'English',
    delete_account:'Delete Account',
    payment_info:'Customer Payment Information',
    booking_details:'Request Details',
    you_rate_text:'You have been rated',
    no_rated_text:'No rating',
    bill_details:'Bill Details',
    your_trip:'Work',
    total_bill:'Total Bill',
    include_tax:'Includes all Taxes',
    total_payable:'My Commision',
    go_to_booking:'Go to Tracking Screen',
    my_booking:'Approved Requests',
    job_ignore:'Do you want to ignore this request?',
    show_modal:'Show Modal',
    notification_title:'Beeplink Notification',
    register:'Register',
    today:'Today\'s Earning',
    thismonth:'This Month\'s Earning',
    totalearning:'Total Earning',
    convenienceFee:'Convenience Fee',
    paymentStatus:'Payment Status',
    payment_mode:'Payment Mode',
    customer_payable:'Customer Payable',
    discount_amount:'Discount Amount',
    CardPaymentAmount:'Pay by card -',
    CashPaymentAmount:'Pay by cash -',
    WalletPayment:'Pay by wallet -',
    android_channel: 'Beeplink Notifications'
}